import type { Cache } from './types';

export const caches: Cache[] = [
  {
    id: 'cipher-cache',
    title: 'Cipher Cache Alpha',
    location: 'Seattle, WA',
    category: 'Electronics',
    rewardSummary: 'Sealed robotics reward revealed only after you check in.',
    description: 'Anonymous donor stocked a mystery item—no assembly or task required. Scan the tag, claim XP, and the reward unlocks on the spot.',
    hint: 'Under the bench near the community garden gate.',
    education: 'Share how you would apply the surprise component once revealed.',
    coordinates: { lat: 47.61, lng: -122.33 },
    xp: 120,
    taskFree: true,
  },
  {
    id: 'vault-beta',
    title: 'Vault Beta Drop',
    location: 'Austin, TX',
    category: 'Mechanical',
    rewardSummary: 'Premium robotics surprise; contents stay secret until claimed.',
    description: 'Find the vault, scan the badge, and your reward is revealed—no puzzles or swaps, just pure discovery and XP.',
    hint: 'Magnetic panel under the pedestrian bridge.',
    education: 'Log how this mystery reward could support a mechanical build of your choice.',
    coordinates: { lat: 30.27, lng: -97.74 },
    xp: 200,
    taskFree: true,
  },
  {
    id: 'signal-quest',
    title: 'Signal Quest Cache',
    location: 'Boston, MA',
    category: 'Programming',
    rewardSummary: 'Tech-forward surprise unlocked on check-in—no coding task needed.',
    description: 'A future-ready robotics goodie waits inside. Check in, claim XP, and the reward details reveal themselves.',
    hint: 'Look for the yellow sticker near the maker-space lockers.',
    education: 'Share a short note about how you might prototype with the mystery item.',
    coordinates: { lat: 42.36, lng: -71.06 },
    xp: 150,
    taskFree: true,
  },
  {
    id: 'guardian-drop',
    title: 'Guardian Drop',
    location: 'Denver, CO',
    category: 'Safety',
    rewardSummary: 'Safety-focused robotics reward—kept secret until you claim it.',
    description: 'No tasks, swaps, or tools needed. Scan the cache tag to unlock your safety-themed surprise and XP.',
    hint: 'Inside the maintenance locker with caution tape.',
    education: 'Log one safety habit you’ll keep using after claiming the reward.',
    coordinates: { lat: 39.74, lng: -104.99 },
    xp: 90,
    taskFree: true,
  },
];

export const featuredCaches = caches.slice(0, 3);
